# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/BTCOM/Desktop/0_Project/ChronoForge-FPGA-Engine/vivado/ChronoForge.cache/wt [current_project]
set_property parent.project_path C:/Users/BTCOM/Desktop/0_Project/ChronoForge-FPGA-Engine/vivado/ChronoForge.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_mem {
  C:/Users/BTCOM/Desktop/0_Project/ChronoForge-FPGA-Engine/mem/attack_object.mem
  C:/Users/BTCOM/Desktop/0_Project/ChronoForge-FPGA-Engine/mem/platform_object.mem
  C:/Users/BTCOM/Desktop/0_Project/ChronoForge-FPGA-Engine/mem/game_manager.mem
}
read_verilog -library xil_defaultlib {
  C:/Users/BTCOM/Desktop/0_Project/ChronoForge-FPGA-Engine/verilog/sources/rom_reader/game_manager_rom_reader.v
  C:/Users/BTCOM/Desktop/0_Project/ChronoForge-FPGA-Engine/verilog/sources/object/object_renderer.v
  C:/Users/BTCOM/Desktop/0_Project/ChronoForge-FPGA-Engine/verilog/sources/object/object_position_controller.v
  C:/Users/BTCOM/Desktop/0_Project/ChronoForge-FPGA-Engine/verilog/sources/top/clk_div.v
  C:/Users/BTCOM/Desktop/0_Project/ChronoForge-FPGA-Engine/verilog/sources/runtime/multi_object_trigger_runtime.v
  C:/Users/BTCOM/Desktop/0_Project/ChronoForge-FPGA-Engine/verilog/sources/runtime/multi_object_collider_runtime.v
  C:/Users/BTCOM/Desktop/0_Project/ChronoForge-FPGA-Engine/verilog/sources/runtime/main_game_runtime.v
  C:/Users/BTCOM/Desktop/0_Project/ChronoForge-FPGA-Engine/verilog/sources/rom_reader/platform_object_rom_reader.v
  C:/Users/BTCOM/Desktop/0_Project/ChronoForge-FPGA-Engine/verilog/sources/rom_reader/attack_object_rom_reader.v
  C:/Users/BTCOM/Desktop/0_Project/ChronoForge-FPGA-Engine/verilog/sources/player/player_renderer.v
  C:/Users/BTCOM/Desktop/0_Project/ChronoForge-FPGA-Engine/verilog/sources/player/player_position_controller.v
  C:/Users/BTCOM/Desktop/0_Project/ChronoForge-FPGA-Engine/verilog/sources/peripherals/vga_translator.v
  C:/Users/BTCOM/Desktop/0_Project/ChronoForge-FPGA-Engine/verilog/sources/peripherals/universal_renderer.v
  C:/Users/BTCOM/Desktop/0_Project/ChronoForge-FPGA-Engine/verilog/sources/game_display/game_display_renderer.v
  C:/Users/BTCOM/Desktop/0_Project/ChronoForge-FPGA-Engine/verilog/sources/game_display/game_display_controller.v
  C:/Users/BTCOM/Desktop/0_Project/ChronoForge-FPGA-Engine/verilog/sources/top/topModule.v
}
read_xdc C:/Users/BTCOM/Desktop/0_Project/ChronoForge-FPGA-Engine/verilog/constrains/constains.xdc
set_property used_in_implementation false [get_files C:/Users/BTCOM/Desktop/0_Project/ChronoForge-FPGA-Engine/verilog/constrains/constains.xdc]

synth_design -top topModule -part xc7a35tcpg236-1
write_checkpoint -noxdef topModule.dcp
catch { report_utilization -file topModule_utilization_synth.rpt -pb topModule_utilization_synth.pb }
